'use client';

import LandingPageFooter from "@/app/_landingpage/LandingPageFooter";
import { useRouter } from "next/navigation";
import React from "react";

function page() {
  const router = useRouter();
  return (
    <div className="bg-gray-50 text-gray-800">
      <header className="bg-white shadow">
        <div className="max-w-6xl mx-auto px-4 py-4 flex justify-between items-center gap-3">
          <img
            alt="TrueReff"
            className="md:w-fit sm:max-w-[203px] w-fit max-w-[160px] mr-auto"
            src="/assets/common/truereff-dark.svg"
            onClick={() => router?.push("/")}
          />
        </div>
      </header>
      <main className="max-w-4xl mx-auto px-4 py-10 space-y-10">
        <section className="space-y-4">
          <p>
            Welcome to Truereff ("Truereff," "we," "our," or "us"). This Privacy
            Policy applies to our app "Truereff," operated by GRIFEN
            INCORPORATED, and available at <strong>truereff.com</strong>. Our app integrates with Instagram via our Facebook App <strong>"truereff_fabk_instg"</strong> to facilitate collaborations between brands and content creators.
          </p>
          <p>
            By accessing or using the Services, you acknowledge that you have
            read, understood, and agreed to the terms of this Privacy Policy. If
            you do not agree with the practices described herein, please do not
            use the Services.
          </p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-blue-600">1. Definitions</h2>
          <ul className="list-disc pl-5 space-y-2">
            <li><strong>Brand</strong>: Any company that registers on the Site to find and collaborate with creators.</li>
            <li><strong>Creator</strong>: An individual registering on the Site to collaborate with brands.</li>
            <li><strong>Personal Information</strong>: Any data that can identify a person, under GDPR/CCPA.</li>
            <li><strong>Meta Platform</strong>: Refers to Meta Platforms, Inc. and affiliated services (Instagram, Facebook).</li>
          </ul>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-blue-600">2. Scope of This Policy</h2>
          <p>This policy applies to Personal Information we process when you use Truereff’s website, tools, and integrations with Meta (e.g., Instagram Graph API).</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-blue-600">3. Information We Collect</h2>
          <p><strong>3.1 Directly from You:</strong></p>
          <ul className="list-disc pl-5">
            <li>Account info (name, email, etc.)</li>
            <li>Profile details and preferences</li>
            <li>Campaign-related data</li>
          </ul>
          <p><strong>3.2 Via Instagram Integration:</strong> Data accessed via Instagram Graph API like public profile, media, comments, and DMs (with user consent).</p>
          <p><strong>3.3 Automatically:</strong> IP, device info, usage data, cookies.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-blue-600">4. Shopify App Integration</h2>
          <p>Our Shopify app, Truereff, integrates with your Shopify store to enable affiliate management and product collaboration through truereff.com. Below, we outline how we collect, use, and share data via this integration.</p>
          <p><strong> Information We Collect</strong><br />When you install Truereff, we access the following information from your Shopify account:</p>
          <p><strong>Shop Domain:</strong> The unique domain of your Shopify store (e.g., yourstore.myshopify.com), used to identify your store for CRM connection.</p>
          <p><strong>Unique ID:</strong> A secure identifier generated by the App to authenticate and connect your Shopify store to truereff.com.</p>
          <p><strong>Product Data:</strong> Information about products in your Shopify store, such as names, prices, descriptions, and images, accessed via Shopify’s APIs to enable product import.</p>
          <p><strong>Order Data:</strong> Information about orders, which may include customer names, shipping addresses, email addresses, order details, and payment information, accessed via Shopify’s APIs for commission tracking.</p>
          <p><strong>Affiliate Tracking Data:</strong> Data collected by a tracking script that runs on your shop’s pages, including affiliate parameters or fingerprints (e.g., UTM parameters, unique identifiers), to track affiliate link performance.</p>
          <p><strong>Usage Data:</strong> Logs of your interactions with the App, such as clicks or navigation, to improve functionality and performance.</p>

          <p><strong>4.b How We Use Your Information</strong></p>
          <ul className="list-disc pl-5">
            <li>Facilitate the connection between your Shopify store and truereff.com, enabling product import, affiliate link generation, discount code creation, commission tracking, and affiliate parameter tracking via the app.</li>
            <li>Provide customer support, troubleshoot issues, and enhance the App’s performance.</li>
            <li>Comply with legal obligations, such as responding to data requests.</li>
            <li>Analyze usage patterns to improve functionality, using aggregated and anonymized data where possible.</li>
          </ul>

          <p><strong>4.c How We Share Your Information</strong></p>
          <ul className="list-disc pl-5">
            <li>We do not sell your personal information. We may share Shopify-related data as follows:</li>
            <li><strong>With truereff.com:</strong> Shop domain, unique ID, product data, order data, and affiliate tracking data are shared with truereff.com for affiliate management and commission tracking.</li>
            <li><strong>With Shopify:</strong> Some data is processed by Shopify per their Privacy Policy.</li>
            <li><strong>Service Providers:</strong> We may share data with trusted providers (e.g., hosting for the tracking script) under confidentiality agreements.</li>
            <li><strong>Legal Requirements:</strong> We may disclose information if required by law.</li>
          </ul>

          <p><strong>4.d Data Security</strong></p>
          <p>We use HTTPS, encryption, and access controls to protect Shopify-related data. The tracking script complies with Shopify’s security standards and respects customer consent.</p>

          <p><strong>4.e Data Retention</strong></p>
          <p>Shopify-related data is retained only as long as necessary for service delivery or legal obligations. Upon app uninstallation, data is deleted within a reasonable period, except where legally required.</p>

          <p><strong>4.f GDPR Compliance</strong></p>
          <p>If your store serves customers in the EEA, UK, or Switzerland, we comply with GDPR by implementing mandatory webhooks for data subject requests (e.g., access, deletion). You, the merchant, are the data controller for customer data, and we act as a data processor, assisting with GDPR obligations.</p>

          <p><strong>4.g Your Rights</strong></p>
          <p>You have rights to access, correct, delete, restrict, or object to data processing. Contact us at <a href="mailto:contact.trf@truereff.com" className="text-blue-500 underline">contact.trf@truereff.com</a> to exercise these rights. We assist with customer data requests as a data processor.</p>
        </section>

        <section className="space-y-4">
          <h2 className="text-xl font-semibold text-blue-600">5. Additional Key Sections</h2>
          <ul className="list-decimal pl-5 space-y-2">
            <li><strong>Legal Basis:</strong> GDPR lawful bases (contract, consent, legal obligation).</li>
            <li><strong>Use of Data:</strong> Managing accounts, campaigns, Instagram interactions, and more.</li>
            <li><strong>Sharing:</strong> Limited to campaign-related parties, service providers, or required by law.</li>
            <li><strong>Meta Compliance:</strong> Follows Meta’s Developer and Data Deletion policies.</li>
            <li><strong>Cookies:</strong> Uses cookies for analytics, personalization, and session management.</li>
            <li><strong>Data Retention:</strong> Data is retained only as long as necessary or legally required.</li>
            <li><strong>Security:</strong> Follows strong encryption and security practices (AES-256, TLS 1.3).</li>
            <li><strong>International Transfers:</strong> Handled via SCCs and appropriate safeguards.</li>
            <li><strong>Your Rights:</strong> Access, correct, delete, restrict, or object to data processing.</li>
            <li><strong>Children:</strong> Not intended for users under 16.</li>
            <li><strong>Third Party Links:</strong> Truereff is not responsible for third-party privacy practices.</li>
            <li><strong>Policy Changes:</strong> Updates will be announced clearly on the platform.</li>
            <li><strong>Contact:</strong> Email: <a href="mailto:contact.trf@truereff.com" className="text-blue-500 underline">contact.trf@truereff.com</a></li>
          </ul>
        </section>
      </main>
      <LandingPageFooter isLanginPage={false} />
    </div>
  );
}

export default page;
