import type { Metadata } from "next";
import NextAuthProvider from "@/lib/context/auth-session-provider";
import Dialogs from "@/lib/components/dialogs";
import "./globals.css";
import { Toaster } from "react-hot-toast";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <NextAuthProvider>
          {children}
          <Dialogs />
          <Toaster position="top-right" />
        </NextAuthProvider>
      </body>
    </html>
  );
}
